### ISSUE TITLE
Regarding the code execution issue2

### ISSUE THREAD

**Issue by chenmo7760** [SFStefenon/Digital_ED#2]
hello, Dr. SFStefenon, I have some queations，Here, following your README, I first ran Sliding Window Compute.py, and then when I executed yolov8-optuna-sd2.py, I noticed that there is no my_rfi.yaml file. Could this be provided? In here, can we see the annotated classes in the dataset? Additionally, in this project, lines do not need to be annotated for YOLOv8 to recognize them, right?
In the YOLO folder, there are only Change_All_the_Classes.py, Change_the_Classes_to_0.py, and Check Class.py. Is the inference script for the trained model located here?thanks very much.

**Comment by SFStefenon** [comment]
I replied on issue1: https://github.com/SFStefenon/Digital_ED/issues/1.
Thank you.
