### ISSUE TITLE
where is your preprint

### ISSUE THREAD

**Issue by chenmo7760** [SFStefenon/Digital_ED#3]
Hello, Dr.Stefano, has your preprint been published?

**Comment by SFStefenon** [comment]
Hello, Yes. You can find it here: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5012234
Thank you.

**Comment by chenmo7760** [comment]
hello , Dr. Stefano, the annotation in Figure 3 should be for “B) lines” , right?

**Comment by chenmo7760** [comment]
hello , Dr. Stefano, can you share the code "Algorithm 1 Ruled-based method to connect symbols."? thanks very much.

**Comment by SFStefenon** [comment]
> hello , Dr. Stefano, the annotation in Figure 3 should be for “B) lines” , right?

Yes, thank you for the remark.

**Comment by SFStefenon** [comment]
> hello , Dr. Stefano, can you share the code "Algorithm 1 Ruled-based method to connect symbols."? thanks very much.

Sure, follow it here: https://github.com/SFStefenon/Digital_ED/blob/main/Graph/Create_Complete_Graph_Full_Image_to_Save_Annotations_and_Segments.py
OBS: These rules consider the data for our railway projects. Specific applications should use their rules. 
Thank you.
